services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080"      # веб-інтерфейс Jenkins тепер на http://localhost:8081
      - "50001:50000"    # агентський порт перенесено на 50001
    volumes:
      - jenkins_home:/var/jenkins_home   # збереження даних Jenkins
      - /var/run/docker.sock:/var/run/docker.sock  # доступ до Docker демона
      - /usr/bin/docker:/usr/bin/docker            # клієнт docker всередині контейнера
    restart: unless-stopped

volumes:
  jenkins_home:
